### ISSUE TITLE
Posting Code

### ISSUE THREAD

**Issue by franTarkenton** [bcgov/nr-rfc-processing#4]
Hey @bsmith-hat and @jsuwala, just checking in to see if you guys can post your code here.  Even if its not working / finished, being able to see it will help us with ideas around the best way to get it deployed in our architecture.  Please let me know if there is anything I can do to facilitate getting code posted to this repo.  Cheers

**Comment by jsuwala** [comment]
Thanks @franTarkenton - I tried creating a README.md file and got the message "You’re making changes in a project you don’t have write access to". Perhaps you can check the access again?

**Comment by franTarkenton** [comment]
Thanks for getting back Jason, when I look at the permission for the repo I have you added with 'write' permissions but it says the invite is pending...  Can you get to this link? https://github.com/bcgov/nr-rfc-processing/invitations

**Comment by jsuwala** [comment]
@franTarkenton  - can you resend the invitation please? I got the message "This invitation has expired."

**Comment by franTarkenton** [comment]
@jsuwala just re-did the invite... let me know if it doesn't work.

**Comment by franTarkenton** [comment]
Hey @jsuwala let me know if there is anything I can do to help get code posted, thx
